name: test Api

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Debug structure
        run: |
          pwd
          ls
          find . -maxdepth 2
          
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          cd $GITHUB_WORKSPACE
          python -m pytest -v

      - name: Basic Import Check
        run: |
          python -c "from app.main import app; print('App import successful')"


  docker-test:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t taxi-api .

      - name: Run Docker Container + Smoke Test
        run: |
          docker run -d -p 8000:8000 --name api taxi-api
          sleep 10
          curl http://localhost:8000/ || exit 1
          docker stop api
